backend/backend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hanabi/', include('hanabi.urls')),
    path('tyjeski/', include('tyjeski.urls')),
    path('', RedirectView.as_view(url='tyjeski/')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

backend/hanabi/urls.py
from django.contrib import admin
from django.urls import path
from hanabi import views

app_name = 'hanabi'
urlpatterns = [
    path('', views.home_action, name='home'),
    path('login', views.login_action, name = 'login'),
    path('logout', views.logout_action, name='logout'),
    path('register', views.register_action, name='register'),
    path('create_room', views.create_room, name='create_room'),
    path('room/<int:room_id>', views.enter_room, name='room'),
    path('join_room', views.join_room, name='join_room'),
    path('play_game/<int:room_id>', views.play_game, name='play_game'),
    path('end_state/<int:room_id>', views.end_state, name='end_state'),
    path('discard_card/<int:room_id>/<int:card_index>', views.discard_card, name='discard_card'),
    path('play_card/<int:room_id>/<int:card_index>', views.play_card, name='play_card'),
    path('give_hint_color/<int:room_id>/<int:card_color>/<int:player_id>', views.give_hint_color, name='give_hint_color'),
    path('give_hint_number/<int:room_id>/<int:card_number>/<int:player_id>', views.give_hint_number, name='give_hint_number'),
    path('get-game-info/<int:room_id>', views.get_game_info),
    path('new', views.interface_overhaul, name='interface-overhaul'),
]

backend/hanabi/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Player(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.OneToOneField(User, default=None, on_delete=models.PROTECT, related_name="player")

    def __str__(self):
        return self.user.get_username()

class Room(models.Model):
    id = models.AutoField(primary_key=True)
    choices = [(2, 2), (3, 3), (4, 4), (5, 5)]
    size = models.IntegerField(choices=choices)
    players = models.ManyToManyField(Player)
    hints = models.IntegerField(default=8)
    strikes = models.IntegerField(default=3)
    game_data = models.JSONField()
    turn = models.IntegerField(default=0)
    active = models.BooleanField(default=False)
    final_turn = models.IntegerField(default=-1)

    def __str__(self):
        return "Room " + str(self.id)

    def increase_hints(self):
        if self.hints < 8:
            self.hints = self.hints + 1
        self.save()
    
    def decrease_hints(self):
        if self.hints > 0:
            self.hints = self.hints - 1
        self.save()

    def use_strike(self):
        self.strikes = self.strikes - 1
        self.save()

    def next_turn(self):
        self.turn = self.turn + 1
        if(self.turn >= self.size):
            self.turn = 0
        self.save()

backend/hanabi/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from hanabi.models import *


class RoomForm(forms.ModelForm):
    class Meta:
        model = Room
        fields = ('size',)


class LoginForm(forms.Form):
    username = forms.CharField(max_length = 20)
    password = forms.CharField(max_length = 200, widget = forms.PasswordInput())

    # Customizes form validation for properties that apply to more
    # than one field.  Overrides the forms.Form.clean function.
    def clean(self):
        # Calls our parent (forms.Form) .clean function, gets a dictionary
        # of cleaned data as a result
        cleaned_data = super().clean()

        # Confirms that the two password fields match
        username = cleaned_data.get('username')
        password = cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        if not user:
            raise forms.ValidationError("Invalid username/password")

        # We must return the cleaned data we got from our parent.
        return cleaned_data


class RegisterForm(forms.Form):
    username   = forms.CharField(max_length = 20)
    password  = forms.CharField(max_length = 200, 
                                 label='Password', 
                                 widget = forms.PasswordInput())
    confirm_password  = forms.CharField(max_length = 200, 
                                 label='Confirm',  
                                 widget = forms.PasswordInput())

    # Customizes form validation for properties that apply to more
    # than one field.  Overrides the forms.Form.clean function.
    def clean(self):
        # Calls our parent (forms.Form) .clean function, gets a dictionary
        # of cleaned data as a result
        cleaned_data = super().clean()

        # Confirms that the two password fields match
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')
        if password and confirm_password and password != confirm_password:
            raise forms.ValidationError("Passwords did not match.")

        # We must return the cleaned data we got from our parent.
        return cleaned_data

    # Customizes form validation for the username field.
    def clean_username(self):
        # Confirms that the username is not already present in the
        # User model database.
        username = self.cleaned_data.get('username')
        if User.objects.filter(username__exact=username):
            raise forms.ValidationError("Username is already taken.")

        # We must return the cleaned data we got from the cleaned_data
        # dictionary
        return username

backend/hanabi/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseForbidden, JsonResponse
from django.core.exceptions import ObjectDoesNotExist
from django.core import serializers
from django.views.decorators.csrf import ensure_csrf_cookie
import json
from hanabi.models import *
from hanabi.forms import *
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
import random
from django.utils import timezone


def login_action(request):
    context = {}

    # Just display the registration form if this is a GET request.
    if request.method == 'GET':
        context['form'] = LoginForm()
        return render(request, 'hanabi/login.html', context)

    # Creates a bound form from the request POST parameters and makes the
    # form available in the request context dictionary.
    form = LoginForm(request.POST)
    context['form'] = form

    # Validates the form.
    if not form.is_valid():
        return render(request, 'hanabi/login.html', context)

    new_user = authenticate(username=form.cleaned_data['username'],
                            password=form.cleaned_data['password'])

    login(request, new_user)
    return redirect(reverse('hanabi:home'))

def logout_action(request):
    logout(request)
    return redirect(reverse('hanabi:login'))

def register_action(request):
    context = {}

    # Just display the registration form if this is a GET request.
    if request.method == 'GET':
        context['form'] = RegisterForm()
        return render(request, 'hanabi/register.html', context)

    # Creates a bound form from the request POST parameters and makes the
    # form available in the request context dictionary.
    form = RegisterForm(request.POST)
    context['form'] = form

    # Validates the form.
    if not form.is_valid():
        return render(request, 'hanabi/register.html', context)

    # At this point, the form data is valid.  Register and login the user.
    new_user = User.objects.create_user(username=form.cleaned_data['username'], 
                                        password=form.cleaned_data['password'])
    new_user.save()
    
    new_user = authenticate(username=form.cleaned_data['username'],
                            password=form.cleaned_data['password'])

    #create profile
    new_player = Player.objects.create(user=new_user)
    new_player.save()

    login(request, new_user)
    return redirect(reverse('hanabi:home'))

@login_required
def home_action(request):
    context = {}
    return render(request, 'hanabi/home.html', context)

@login_required
def create_room(request):
    context = {}
    if request.method == 'GET':
        context['form'] = RoomForm()
        return render(request, 'hanabi/create_room.html', context)
    form = RoomForm(request.POST)
    context['form'] = form
    if not form.is_valid():
        return render(request, 'hanabi/create_room.html', context)
    new_room = Room()
    new_room.size = form.cleaned_data['size']
    #white = 1, yellow = 2, green = 3, blue = 4, red = 5
    #first index is color, 2nd index is number
    data = {
        "deck" :   [[1, 1], [1, 1], [1, 1], [1, 2], [1, 2], [1, 3], [1, 3], [1, 4], [1, 4], [1, 5],
                    [2, 1], [2, 1], [2, 1], [2, 2], [2, 2], [2, 3], [2, 3], [2, 4], [2, 4], [2, 5],
                    [3, 1], [3, 1], [3, 1], [3, 2], [3, 2], [3, 3], [3, 3], [3, 4], [3, 4], [3, 5],
                    [4, 1], [4, 1], [4, 1], [4, 2], [4, 2], [4, 3], [4, 3], [4, 4], [4, 4], [4, 5],
                    [5, 1], [5, 1], [5, 1], [5, 2], [5, 2], [5, 3], [5, 3], [5, 4], [5, 4], [5, 5]],

        "hands" : {},
        "discard" : [],
        "tabletop" : [0, 0, 0, 0, 0],
        "log": [],
        "end_game": []
    }

    random.shuffle(data["deck"])
    hand_size = 5
    if new_room.size > 3:
        hand_size = 4

    player = Player.objects.get(user=request.user)
    data["hands"][str(player.id)] = []
    for _ in range(hand_size):
        data["hands"][str(player.id)].append(data["deck"].pop())

    new_room.game_data = json.dumps(data)

    new_room.save()
    #The person who made the room is added as one of the players
    new_room.players.add(Player.objects.get(user=request.user))
    room_id = new_room.id
    return redirect(reverse('hanabi:room', args=(room_id,)))

@login_required
def enter_room(request, room_id):
    context = {}
    room = Room.objects.get(id=room_id)
    players = room.players.all()
    context['players'] = players
    context['room'] = room
    player_self = Player.objects.get(user=request.user)
    context['player_self'] = player_self
    context['playing'] = player_self in players

    return render(request, 'hanabi/room.html', context)

@login_required
def play_game(request, room_id):
    room = Room.objects.get(id=room_id)
    player = Player.objects.get(user=request.user)
    
    # Cannot join if the game is full or player is already playing
    if room.players.filter(user=request.user) or room.players.count() >= room.size:
        return redirect(reverse('hanabi:room', args=(room_id,)))
    
    room.players.add(player)
    if room.players.count() >= room.size:
        room.active = True

    #grab a hand of cards
    data = json.loads(room.game_data)

    hand_size = 5
    if room.size > 3:
        hand_size = 4

    data["hands"][str(player.id)] = []
    for _ in range(hand_size):
        data["hands"][str(player.id)].append(data["deck"].pop())

    room.game_data = json.dumps(data)
    room.save()
    #
    return redirect(reverse('hanabi:room', args=(room_id,)))

@login_required
def join_room(request):
    context = {}
    rooms = []
    for room in Room.objects.all():
        rooms.append(room)
    context['rooms'] = rooms
    return render(request, 'hanabi/join_room.html', context)

def get_color_string(color_number):
    if color_number == 1:
        return "white"
    if color_number == 2:
        return "yellow"
    if color_number == 3:
        return "green"
    if color_number == 4:
        return "blue"
    if color_number == 5:
        return "red"
    return ""

@login_required
def discard_card(request, room_id, card_index):
    room = Room.objects.get(id=room_id)
    player = Player.objects.get(user=request.user)
    players = room.players.all()
    #It must be the player's turn to take an action
    if player != players[room.turn] or not room.active:
        return redirect(reverse('hanabi:room', args=(room_id,)))

    data = json.loads(room.game_data)
    hand = data["hands"][str(player.id)]
    card = hand[card_index]

    # Discarding a card grants a hint
    data["discard"].append(card)
    room.increase_hints()
    # Draw a new card to replace the discarded card
    if len(data["deck"]) > 0:
        hand[card_index] = data["deck"].pop()
    else:
        del hand[card_index]

    # Write action to the log
    log_text = player.user.username + " discarded the " + get_color_string(card[0]) + " " + str(card[1])
    data["log"].append(log_text)

    room.next_turn()
    room.game_data = json.dumps(data)
    room.save()

    # Check whether the game is over
    return end_state(request, room_id)

@login_required
def play_card(request, room_id, card_index):
    room = Room.objects.get(id=room_id)
    player = Player.objects.get(user=request.user)
    players = room.players.all()
    #It must be the player's turn to take an action
    if player != players[room.turn] or not room.active:
        return redirect(reverse('hanabi:room', args=(room_id,)))

    data = json.loads(room.game_data)
    hand = data["hands"][str(player.id)]
    card = hand[card_index]

    # If the played card is the next in the sequence, add it to the table.
    # Otherwise a fuse token is used and the card is sent to the discard pile
    if card[1] == data["tabletop"][card[0] - 1] + 1:
        data["tabletop"][card[0] - 1] += 1
        # Completing a color grants a hint token
        if card[1] == 5:
            room.increase_hints()
    else:
        room.use_strike()
        data["discard"].append(card)

    # Draw a card to replace the played card
    if len(data["deck"]) > 0:
        hand[card_index] = data["deck"].pop()
    else:
        del hand[card_index]

    # Write action to the log
    log_text = player.user.username + " played the " + get_color_string(card[0]) + " " + str(card[1])
    data["log"].append(log_text)

    room.next_turn()
    room.game_data = json.dumps(data)
    room.save()

    # Check whether the game is over
    return end_state(request, room_id)

@login_required
def give_hint_color(request, room_id, card_color, player_id):
    #white = 1, yellow = 2, green = 3, blue = 4, red = 5
    total_colors = 0
    indices = []
    room = Room.objects.get(id=room_id)
    self_player = Player.objects.get(user=request.user)
    player = Player.objects.get(id=player_id)
    players = room.players.all()

    #It must be the player's turn to take an action
    if self_player != players[room.turn] or not room.active:
        return redirect(reverse('hanabi:room', args=(room_id,)))

    #cannot give a hint without a token
    if room.hints <= 0:
        return redirect(reverse('hanabi:room', args=(room_id,)))

    data = json.loads(room.game_data)
    hand = data["hands"][str(player_id)]
    hint_color = card_color
    #send player, indices of card, and message
    for i in range(len(hand)):
        if hand[i][0] == hint_color:
            indices.append(i+1)

    player_username = player.user.username

    color = get_color_string(hint_color)
    message = ""
    if len(indices) == 1:
        message = "Card " + str(indices[0]) + " is " + color + " for " + player_username
    else:
        mini = ""
        for i in range(len(indices) - 1):
            mini += str(indices[i]) + ", "
        mini += str(indices[-1]) + " "

backend/hanabi/templates/hanabi/base.html
<!doctype html>
<html>
	<head>
	    <meta charset="utf-8">
	    {% load static %}
		<link href="{% static 'hanabi/css/base.css' %}" rel="stylesheet" type="text/css">
        {% block header %}
		{% endblock %}
		<title> Hanabi Online </title>
	</head>

	<body>
		<div class="user-info">
			<div>
				<a href="{% url 'hanabi:home' %}">Home</a>
				<a href="{% url 'hanabi:logout' %}">Logout</a>
			</div>
		
			<span> {{user.username}} </span>	
		</div>
        {% block content %}
		{% endblock %}
    </body>
</html>

backend/hanabi/templates/hanabi/create_room.html
{% extends "hanabi/base.html" %}

{% block header %}
    {% load static %}
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"
        integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
        crossorigin="anonymous"></script>
{% endblock %}

{% block content %}
    <form class="add-form" action="{% url 'hanabi:create_room' %}" method="post">
        <p>Choose size</p> {{ form.size}}
        <button type="submit" id = "id_post_button">Submit</button>
        {% csrf_token %}
    </form>
{% endblock %}

backend/hanabi/templates/hanabi/home.html
{% extends "hanabi/base.html" %}

{% block content %}
	<div class="big-heading">
		Hanabi Online
	</div>

	<div class="center">
		<div>
			<form action="{% url 'hanabi:create_room' %}">
			<button class="big-button" type="submit"> Create a Room </button> 
			</form>
		</div>
		<div>
			<form action="{% url 'hanabi:join_room' %}">
			<button class="big-button" type="submit">Join a Room </button> 
			</form>
		</div>
	</div>
	<a href="{% url 'hanabi:interface-overhaul' %}">NEW LOOK (use phone)</a>
{% endblock %}

backend/hanabi/templates/hanabi/interface-overhaul.html
<!doctype html>
<html lang="en">

<head>
  {% load static %}
  <!-- Required Meta Tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Hanabi</title>
  <link rel="stylesheet" href="{% static 'hanabi/css/interface-overhaul.css' %}" type="text/css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css"
    integrity="sha512-0S+nbAYis87iX26mmj/+fWt1MmaKCv80H+Mbo+Ne7ES4I6rxswpfnC6PxmLiw33Ywj2ghbtTw0FkLbMWqh4F7Q=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>

<body>
  <!-- HEADER -->
  <div class="header">
    <!-- Played Cards -->
    <div class="played-cards">
      <div class="played-cards__title">Played Cards</div>
      <div class="played-cards__display">
        <div class="played-cards__display--stack">
          <div class="card r1"></div>
          <div class="card r2"></div>
          <div class="card r3"></div>
          <div class="card r4"></div>
          <div class="card r5"></div>
        </div>
        <div class="played-cards__display--stack">
          <div class="card b5"></div>
        </div>
        <div class="played-cards__display--stack">
          <div class="card g5"></div>
        </div>
        <div class="played-cards__display--stack">
          <div class="card y5"></div>
        </div>
        <div class="played-cards__display--stack">
          <div class="card p5"></div>
        </div>
      </div>
    </div>
    <!-- Discarded Cards -->
    <div class="discarded-cards">
      <div class="discarded-cards__title">Discarded Cards</div>
      <div class="discarded-cards__display">
        <div class="discarded-cards__display--stack">
          <div class="card r1"></div>
          <div class="card b2"></div>
          <div class="card g3"></div>
        </div>
      </div>
      <div class="discarded-cards__popout-icon">
        <i class="fas fa-chevron-left"></i>
      </div>
    </div>
  </div>

  <!-- CONTENT -->
  <div class="content">
    <div>
      <div class="player-name">Player 1</div>
      <div class="player-container">
          <div class="player-hand">
            <div class="card r1"></div>
            <div class="card r2"></div>
            <div class="card r3"></div>
            <div class="card r4"></div>
          </div>
          <div class="player-text">Hello!</div>
      </div>
    </div>

    <div>
      <div class="player-name">Player 2</div>
      <div class="player-container">
        <div class="player-hand">
          <div class="card b1"></div>
          <div class="card b2"></div>
          <div class="card b3"></div>
          <div class="card b4"></div>  
        </div>
        <div class="player-text">Hello!</div>
      </div>
    </div>

    <div>
      <div class="player-name">Player 3</div>
      <div class="player-container">
        <div class="player-hand">
          <div class="card g1"></div>
          <div class="card g2"></div>
          <div class="card g3"></div>
          <div class="card g4"></div>
        </div>
        <div class="player-text">Hello!</div>
      </div>
    </div>

    <div>
      <div class="player-name">Player 4</div>
      <div class="player-container">
        <div class="player-hand">
          <div class="card y1"></div>
          <div class="card y2"></div>
          <div class="card y3"></div>
          <div class="card y4"></div>
        </div>
        <div class="player-text">Hello!</div>
      </div>
    </div>

    <div>
      <div class="player-name">Player 5</div>
      <div class="player-container">
        <div class="player-hand">
          <div class="card p1"></div>
          <div class="card p2"></div>
          <div class="card p3"></div>
          <div class="card p4"></div>
        </div>
        <div class="player-text">Player 4 has five yellow cards</div>
      </div>
    </div>
  </div>

  <!-- FOOTER -->
  <div class="game-info">
    <div class="icon-wrapper">
      <div class="icon heart-icon">
        <div class="icon__counter">2</div>
      </div>
      <div class="icon-label">Lives</div>
    </div>
    <div class="icon-wrapper">
      <div class="icon hint-icon">
        <div class="icon__counter">5</div>
      </div>
      <div class="icon-label">Hints</div>
    </div>
    <div class="icon-wrapper">
      <div class="icon deck-icon">
        <div class="icon__counter">23</div>
      </div>
      <div class="icon-label">Deck</div>
    </div>
  </div>
</body>

</html>

backend/hanabi/templates/hanabi/join_room.html
{% extends "hanabi/base.html" %}

{% block header %}
    {% load static %}
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"
        integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
        crossorigin="anonymous"></script>
{% endblock %}
	
{% block content %}
    <div> Join a Room </div>
    <ul>
    {% for room in rooms %}
        <li>
            <a href = "{% url 'hanabi:room' room.id %}">Room {{room.id}}</a>
            <span> {{ room.players.all|length }}/{{ room.size }} </span>
        </li>
    {% endfor %}
    </ul>
{% endblock %}

backend/hanabi/templates/hanabi/login.html
<!doctype html>
<html>
	<head>
	    <meta charset="utf-8">
	    {% load static %}
		<link href="{% static 'hanabi/css/base.css' %}" rel="stylesheet" type="text/css">
		<title> Hanabi Online </title>
	</head>

    <body>
        <a href="{% url 'hanabi:register' %}">
            <button id = "id_register_link">Register</button>
        </a>

        <div id="id_page_name">Login</div>

        <form method="post" action="{% url 'hanabi:login' %}">
            <table>
                {{form}}
            </table>
            {% csrf_token %}
            <button type="submit" id = "id_login_button">Submit</button>
        </form>
    </body>
</html>

backend/hanabi/templates/hanabi/register.html
<!doctype html>
<html>
	<head>
	    <meta charset="utf-8">
	    {% load static %}
		<link href="{% static 'hanabi/css/base.css' %}" rel="stylesheet" type="text/css">
		<title> Hanabi Online </title>
	</head>

    <body>
        <a href="{% url 'hanabi:login' %}">
            <button id = "id_login_link">Login</button>
        </a>
    
        <div id="id_page_name">Register</div>

        <form method="post" action="{% url 'hanabi:register' %}">
            <table>
                {% for field in form.visible_fields %}
                    <tr>
                        <td>{{field.label_tag}}</td>
                        <td>{{field}}</td>
                        <td class="errorlist">
                            {% for error in field.errors %} {{error}} {% endfor %}
                        </td>
                    </tr>
                {% endfor %}
            </table>
            {% csrf_token %}
            <button type="submit" id = "id_register_button">Submit</button>
        </form>

        {% for error in form.non_field_errors %}
            <p class="errorlist">
                {{ error }}
            </p>
        {% endfor %}
    </body>
</html>

backend/hanabi/templates/hanabi/room.html
{% extends "hanabi/base.html" %}

{% block header %}
	{% load static %}
	<script src="{% static 'hanabi/js/game.js' %}" type="text/javascript"></script>
{% endblock %}

{% block content %}
	<b> Tabletop </b>
	<ul class="tabletop" id="id_tabletop">
	</ul>
	<div class="sub-title"> Current players </div>
	<div class = "sidebar_wrapper">
		<b class = "text-hints"> Hints</b>
		<div class="hints" id="id_hints"></div>
		<b class = "text-strikes">Fuses</b>
		<div class="strikes" id="id_strikes"></div>
		<b class="text-deck">Deck</b>
		<div class="deck" id="id_deck_size"></div>
	</div>
	<ol id="id_hands">
	</ol>

	{% if room.size > players|length and not playing %}
        <a href="{% url 'hanabi:play_game' room.id %}">
			<button>Join</button>
		</a>
    {% endif %}

	<div id="id_room_message">
	</div>

	<ul id = "id_log"> 
	</ul>

	<b> Discard Pile </b>
	<ul class="discard" id="id_discard">
	</ul>	

	<script>
		var room_id = "{{ room.id }}"

		window.onload = getGameInfo;
		window.setInterval(getGameInfo, 5000);
	</script>

{% endblock %}