backend/backend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hanabi/', include('hanabi.urls')),
    path('tyjeski/', include('tyjeski.urls')),
    path('', RedirectView.as_view(url='tyjeski/')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

backend/hanabi/urls.py
from django.contrib import admin
from django.urls import path
from hanabi import views

app_name = 'hanabi'
urlpatterns = [
    path('', views.home_action, name='home'),
    path('login', views.login_action, name = 'login'),
    path('logout', views.logout_action, name='logout'),
    path('register', views.register_action, name='register'),
    path('create_room', views.create_room, name='create_room'),
    path('room/<int:room_id>', views.enter_room, name='room'),
    path('join_room', views.join_room, name='join_room'),
    path('play_game/<int:room_id>', views.play_game, name='play_game'),
    path('end_state/<int:room_id>', views.end_state, name='end_state'),
    path('discard_card/<int:room_id>/<int:card_index>', views.discard_card, name='discard_card'),
    path('play_card/<int:room_id>/<int:card_index>', views.play_card, name='play_card'),
    path('give_hint_color/<int:room_id>/<int:card_color>/<int:player_id>', views.give_hint_color, name='give_hint_color'),
    path('give_hint_number/<int:room_id>/<int:card_number>/<int:player_id>', views.give_hint_number, name='give_hint_number'),
    path('get-game-info/<int:room_id>', views.get_game_info),
    path('new', views.interface_overhaul, name='interface-overhaul'),
]

backend/tyjeski/urls.py
from django.urls import path
from . import views

app_name = 'tyjeski'
urlpatterns = [
    path('', views.home, name='home'),
    path('portfolio-01', views.portfolio_01, name='portfolio-01'),
    path('portfolio-02', views.portfolio_02, name='portfolio-02'),
    path('portfolio-03', views.portfolio_03, name='portfolio-03'),
    path('portfolio-04', views.portfolio_04, name='portfolio-04'),
]

backend/tyjeski/models.py
from django.db import models

# Create your models here.

backend/tyjeski/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, 'tyjeski/index.html')

def portfolio_01(request):
    return render(request, 'tyjeski/portfolio-item-01.html')

def portfolio_02(request):
    return render(request, 'tyjeski/portfolio-item-02.html')

def portfolio_03(request):
    return render(request, 'tyjeski/portfolio-item-03.html')

def portfolio_04(request):
    return render(request, 'tyjeski/portfolio-item-04.html')

backend/tyjeski/templates/tyjeski/base.html
<!doctype html>
<html lang="en">

<head>
  {% load static %}
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Tyjeski Website</title>
  <link rel="shortcut icon" type="image/png" href="{% static 'tyjeski/img/favicon.ico' %}"/>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/7.0.0/normalize.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css"
    integrity="sha512-0S+nbAYis87iX26mmj/+fWt1MmaKCv80H+Mbo+Ne7ES4I6rxswpfnC6PxmLiw33Ywj2ghbtTw0FkLbMWqh4F7Q=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
  <link href="https://fonts.googleapis.com/css?family=Source+Code+Pro:400,900|Source+Sans+Pro:300,900&display=swap"
    rel="stylesheet">

  <link rel="stylesheet" href="{% static 'tyjeski/css/style.css' %}" type="text/css">

</head>

<body>
  <header>
    <div class="logo">
      <img src="{% static 'tyjeski/img/logo.png' %}" alt="">
    </div>
    <button class="nav-toggle" aria-label="toggle navigation">
      <span class="hamburger"></span>
    </button>
    <nav class="nav">
      <ul class="nav__list">
        <li class="nav__item"><a href="{% url 'tyjeski:home' %}" class="nav__link">Home</a></li>
        <li class="nav__item"><a href="{% url 'tyjeski:home' %}#services" class="nav__link">My Services</a></li>
        <li class="nav__item"><a href="{% url 'tyjeski:home' %}#about" class="nav__link">About Me</a></li>
        <li class="nav__item"><a href="{% url 'tyjeski:home' %}#work" class="nav__link">My Work</a></li>
      </ul>
    </nav>
  </header>

  {% block content %}
  {% endblock %}

  <!-- Footer -->
  <footer class="footer">
    <a href="mailto:atyjeski@gmail.com" class="footer__link">atyjeski@gmail.com</a>
    <ul class="social-list">
      <li class="social-list__item">
        <a class="social-list__link" href="https://github.com/atyjeski/tyjeski">
          <i class="fab fa-github"></i>
        </a>
      </li>
    </ul>
  </footer>

  <script src="{% static 'tyjeski/js/index.js' %}"></script>

</body>

</html>

backend/tyjeski/templates/tyjeski/index.html
{% extends 'tyjeski/base.html' %}
{% load static %}

{% block content %}
<!-- Introduction -->
<section class="intro" id="home">
  <h1 class="section__title section__title--intro">
    Hi, I am <strong>Andres Tyjeski</strong>
  </h1>
  <p class="section__subtitle section__subtitle--intro">the maker of this website</p>
  <img src="{% static 'tyjeski/img/andres-01.png' %}" alt="a picture of Andres Tyjeski" class="intro__img">
</section>

<!-- My Services -->
<section class="my-services" id="services">
  <h2 class="section__title section__title--services">What I do</h2>
  <div class="services">
    <!-- Service 1 -->
    <div class="service">
      <h3>Service 1</h3>
      <p>Service 1 text</p>
    </div>
    <!-- Service 2 -->
    <div class="service">
      <h3>Service 2</h3>
      <p>Service 2 Text</p>
    </div>
    <!-- Service 3 -->
    <div class="service">
      <h3>Service 3</h3>
      <p>Service 3 Text</p>
    </div>

  </div>

  <a href="#work" class="btn">My Work</a>
</section>

<!-- About Me -->
<section class="about-me" id="about">
  <h2 class="section__title section__title--about">Who I am</h2>
  <p class="section__subtitle section__subtitle--about">Cool Guy</p>

  <div class="about-me__body">
    <p>This is the paragraph where I talk about myself</p>
  </div>

  <img src="{% static 'tyjeski/img/andres-02.png' %}" alt="another picture of Andres" class="about-me__img">
</section>

<!-- My Work -->
<section class="my-work" id="work">
  <h2 class="section__title section__title--work">My work</h2>
  <p class="section__subtitle section__subtitle--work">A selection of my range of work</p>

  <div class="portfolio">
    <!-- Portfolio Item 1 -->
    <a href="{% url 'tyjeski:portfolio-01' %}" class="portfolio__item">
      <img src="{% static 'tyjeski/img/portfolio-01.png' %}" alt="" class="portfolio__img">
    </a>
    <!-- Portfolio Item 2 -->
    <a href="{% url 'tyjeski:portfolio-02' %}" class="portfolio__item">
      <img src="{% static 'tyjeski/img/portfolio-02.png' %}" alt="" class="portfolio__img">
    </a>
    <!-- Portfolio Item 3 -->
    <a href="{% url 'tyjeski:portfolio-03' %}" class="portfolio__item">
      <img src="{% static 'tyjeski/img/portfolio-03.png' %}" alt="" class="portfolio__img">
    </a>
    <!-- Portfolio Item 4 -->
    <a href="{% url 'tyjeski:portfolio-04' %}" class="portfolio__item">
      <img src="{% static 'tyjeski/img/portfolio-04.png' %}" alt="" class="portfolio__img">
    </a>
  </div>
</section>
{% endblock %}

backend/tyjeski/templates/tyjeski/portfolio-item-01.html
{% extends 'tyjeski/base.html' %}
{% load static %}

{% block content %}
<!-- Introduction -->
<section class="intro">
    <h1 class="section__title section__title--intro">
        The title <strong>of my project</strong>
    </h1>
    <p class="section__subtitle section__subtitle--intro">a short subtitle</p>
    <img src="{% static 'tyjeski/img/portfolio-01.png' %}" alt="" class="intro__img">
</section>

<div class="portfolio-item-individual">
    <p>paragraph</p>
    <img src="{% static 'tyjeski/img/portfolio-details.jpeg' %}" alt="">
    <p>paragraph</p>
    <p>paragraph</p>

    <a href="{% url 'hanabi:home' %}"> HANABI DEMO </a>
</div>

{% endblock %}

backend/tyjeski/templates/tyjeski/portfolio-item-02.html
{% extends 'tyjeski/base.html' %}
{% load static %}

{% block content %}
<!-- Introduction -->
<section class="intro">
    <h1 class="section__title section__title--intro">
        The title <strong>of my project</strong>
    </h1>
    <p class="section__subtitle section__subtitle--intro">a short subtitle</p>
    <img src="{% static 'tyjeski/img/portfolio-02.png' %}" alt="" class="intro__img">
</section>

<div class="portfolio-item-individual">
    <p>paragraph</p>
    <img src="{% static 'tyjeski/img/portfolio-details.jpeg' %}" alt="">
    <p>paragraph</p>
    <p>paragraph</p>
</div>

{% endblock %}

backend/tyjeski/templates/tyjeski/portfolio-item-03.html
{% extends 'tyjeski/base.html' %}
{% load static %}

{% block content %}
<!-- Introduction -->
<section class="intro">
    <h1 class="section__title section__title--intro">
        The title <strong>of my project</strong>
    </h1>
    <p class="section__subtitle section__subtitle--intro">a short subtitle</p>
    <img src="{% static 'tyjeski/img/portfolio-03.png' %}" alt="" class="intro__img">
</section>

<div class="portfolio-item-individual">
    <p>paragraph</p>
    <img src="{% static 'tyjeski/img/portfolio-details.jpeg' %}" alt="">
    <p>paragraph</p>
    <p>paragraph</p>
</div>

{% endblock %}

backend/tyjeski/templates/tyjeski/portfolio-item-04.html
{% extends 'tyjeski/base.html' %}
{% load static %}

{% block content %}
<!-- Introduction -->
<section class="intro">
    <h1 class="section__title section__title--intro">
        The title <strong>of my project</strong>
    </h1>
    <p class="section__subtitle section__subtitle--intro">a short subtitle</p>
    <img src="{% static 'tyjeski/img/portfolio-04.png' %}" alt="" class="intro__img">
</section>

<div class="portfolio-item-individual">
    <p>paragraph</p>
    <img src="{% static 'tyjeski/img/portfolio-details.jpeg' %}" alt="">
    <p>paragraph</p>
    <p>paragraph</p>
</div>

<iframe width="420" height="315"
    src="https://www.youtube.com/embed/tgbNymZ7vqY">
</iframe>

{% endblock %}